### PR TITLE
⚙️Misc cleanup

### LINKED ISSUE #295: ⚙️Misc cleanup
### Complete The Item Below

- [X] I have updated the title without removing the ⚙️ emoji.

### Description

Remove the `manual-testing` directory and all of its contents from the repository.

This will also require updating various configuration files.

1. Update the `reload-cache` deno task like the following below:
    ```diff
    - "reload-cache": "deno cache -r './.github/cicd/core/**/*.ts' './.github/cicd/manual-testing/**/*.ts' './.github/cicd/scripts/**/*.ts'"
    + "reload-cache": "deno cache -r './.github/cicd/core/**/*.ts' './.github/cicd/scripts/**/*.ts'"
    ```
2. In the _**launch.json**_ config file, remove the launch config object below:
    ```json
    { // RESET DOCS
        "request": "launch",
        "name": "Reset Docs",
        "type": "node",
        "program": "${workspaceFolder}/.github/cicd/manual-testing/reset-docs.ts",
        "cwd": "${workspaceFolder}/.github/cicd",
        "runtimeExecutable": "${userHome}/.deno/bin/deno.EXE",
        "runtimeArgs": [
            "run",
            "--inspect-wait",
            "--allow-all",
        ],
        "attachSimplePort": 9229
    },
    ```
3. In the _**tasks.json**_ config file, remove the config object below:
    ```json
    { // RESET DOCS
	    "label": "Reset Docs",
	    "detail": "Resets the docs to the default state.",
	    "type": "shell",
	    "options": {
		    "cwd": "${workspaceFolder}/.github/cicd"
	    },
	    "command": "deno",
	    "args": [
		    "run",
		    "--allow-read",
		    "--allow-write",
		    "'${workspaceFolder}/.github/cicd/manual-testing/reset-docs.ts'"
	    ]
    },
    ```
5. Remove the _**reset-docs.ts**_ file.

### Acceptance Criteria

```[tasklist]
- [x] The `reload-cache` deno task has been updated
- [x] Launch config has been removed
- [x] Task config has been removed
```

### ToDo items

```[tasklist]
- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] A priority label was added to this issue.  Refer to the _**Priority Type Labels**_ section below.
```

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

|--------------|---------------------------------------------------------------------------------------------------|
| CICD                 | https://github.com/KinsonDigital/VelaptorDocs/labels/cicd                                 |
| Dependency Update    | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%A6dependency-update        |
| Miscellaneous        | https://github.com/KinsonDigital/VelaptorDocs/labels/miscellaneous                        |
| Guide Doc Changes | https://github.com/KinsonDigital/VelaptorDocs/labels/%F0%9F%93%9Cguide-doc-changes           |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                                  |
|---------------------|------------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/VelaptorDocs/labels/low-priority    |
| Medium Priority     | https://github.com/KinsonDigital/VelaptorDocs/labels/medium-priority |
| High Priority       | https://github.com/KinsonDigital/VelaptorDocs/labels/high-priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### PR DESCRIPTION
**Pull request by LeaDevelop**
### **Description:**

To allow this pull request to be merged, please make sure that the following items of this pull request are complete.

This pull request closes #295

✅The pull request head branch must be a feature branch with the syntax 'feature/<issue-num>-sync-testing'.  
✅The pull request base branch must be a 'main' or 'preview' branch..  
✅The pull request head branch contains a valid issue number.  
✅The pull request title matches the linked issue title exactly.  
✅The pull request assignees match the assignees of the issue.  
✅The pull request labels match the labels of the issue.  
✅The pull request organizational projects match the organizational projects of the issue.  
✅The pull requests milestone matches the milestone of the issue.  

---

### **Additional Info:**
1. Pull requests are automatically synced with the associated issue upon creation by one of the KinsonDigital workflow bots. 
2. The associated issue is the issue number that is embedded in the pull request head branch.
3. The list above will be automatically updated as the pull request's various settings match or do not match the associated issue.
4. To manually sync the pull request to the issue, create a comment with the `[run-sync]` command.
	> **Note** You must be an admin member of the organization to use this command.

---

- [x] Sync with the issue.  Use this to enable or disable this pull request from syncing with its associated issue.

### CODE REVIEW

**Comment by CalvinWilkinson** [comment]
[run-sync]

**Comment by LeaDevelop** [comment]
I'll have time throughout the weekend again to check failures, today won't work out sadly.

**Comment by LeaDevelop** [comment]
I see, so I was on right track PR name and alignment with main was on todo, noted the name for future and apologies for the inconvenience 😊

**Comment by CalvinWilkinson** [comment]
> I see, so I was on right track PR name and alignment with main was on todo, noted the name for future and apologies for the inconvenience 😊

Oh, no worries at all @LeaDevelop. That is my fault.  I have a custom system that I built that automatically syncs issues with pull requests, but this repository was not really fully "set up" for outside contributors.  The system did not kick in which is why the pull request description was empty.  

100% my fault!

All of my CICD infrastructure is pretty advanced and involved in keeping things smooth across the entire organization for all of my projects.  It is always a work in progress.  

This is the first year I have had outside contributors to the docs website. The previous 2 years were with Velaptor and CASL

**Review by CalvinWilkinson — APPROVED** [review]

**Review by KinsonDigitalAdmin — APPROVED** [review]

**Pull request merged**
